---
# default settings
env:
    browser: true
    es6: true
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module

# needed for TypeScript + prettier
extends:
    - plugin:prettier/recommended
    - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
    - prettier

# TODO: think abount standards
rules:
    no-console: 0
    no-unused-vars: 1
    prettier/prettier:
        - error
        - arrowParens: always
          bracketSpacing: true
          printWidth: 100
          semi: false
          singleQuote: true
